[package]
name = "imt-cli"
version = "0.1.0"
authors = ["7db9a"]
edition = "2018"

[[bin]]
name = "imt-cli"
path = "src/bin/main.rs"
doc = false

[lib]
name = "imt_cli"
path = "src/mod.rs"

[dependencies]
runas = "0.2.1"
seahorse = "0.7.1"
